### PR TITLE
Optimized floating point routines: addition, multiplication, and SQR.

### PR DESCRIPTION
**Pull request by MJoergen**
This adresses issue #67 .

The speedup is approximately:
Addition : 10 %
Multiplication : 25 %
SQR : 80 %

In the directory test/ there are some benchmarks.

I've removed the floating point routine "mltply" from the jump table. It is not used anywhere in the ROM, and the optimized multiplication routine does not support it.

### CODE REVIEW

**Comment by mist64** [comment]
This looks awesome! Do you want to add your name and a license to the new files?

In KERNAL, I use a comment on the top of the file like this:

```
;----------------------------------------------------------------------
; Console Library
;----------------------------------------------------------------------
; (C)2020 Michael Steil, License: 2-clause BSD

```

**Comment by MJoergen** [comment]
@mist64 Yes, please add a license similar to the KERNAL, and include my name: Michael Jørgensen

**Comment by mist64** [comment]
I just did a naive test of my own:

`A=1:FORI=1TO10000:A=A*1.0001:NEXT:?A`

The results with and without optimizations differ in the 8th digit after the decimal point.

Are the optimizations supposed to generate the exact same results?

**Comment by MJoergen** [comment]
@mist64 Ideally yes, except that I fixed a bug in the original version of multiply:

If you try the following, then the original ROM will give two different results (one correct, the other incorrect):
A=16777217
PRINT 10*A
PRINT A*10

This I have fixed in my re-implementation of multiply, so this will certainly generate different results.

This is even more apparent in the SQR function, which will generate different (and more accurate) results than the ROM. For instance, SQR(9)-3 yields a non-zero result in the original ROM, but gives zero with my re-implementation.

In your naive test, what results did you get?

**Comment by mist64** [comment]
```
before: 2.71814133
after:  2.71814132

```

**Comment by mist64** [comment]
I merged it, and added a copyright/author/license header to all FPLIB source files in a separate commit.

This is very cool! Code from 1978 *significantly* optimized! :)

**Comment by mist64** [comment]
Also, your patch fixes the C64 BASIC [Multiply Bug](https://www.c64-wiki.com/wiki/Multiply_bug)!

**Pull request merged**
