### PR TITLE
New audio bank and API

### LINKED ISSUE #330: reset doesn't silence the vera PSG
When vera PSG is making sounds, a RESET command issued on Basic, or a call to the system reset vector, does't silence the PSG.   Also writing 1 to the Vera RESET bit in $9f25 doesn't silence the PSG!  

Is this a kernal issue or a Vera issue? I assumed all vera registers would be reset to default state when resetting the vera?

pressing CTRL-R in the emulator *does* however, i don't really know why?

### PR DESCRIPTION
**Pull request by mooinglemur**
First of all, my apologies for the size of this PR.  This has been a fairly substantial effort and a lot more of this API came together more quickly than anticipated, and I believe it is feature complete with what @ZeroByteOrg @jestin and I have set out to do, and then some.

This closes https://github.com/commanderx16/x16-rom/issues/330 as this bank's init API is called from the KERNAL's reset handler.

Other than the init routine, we've tried to touch the other banks as little as possible.  We took 2 bytes of zeropage at the end of the reserved KERNAL area ($A7-$A8).  We reserved a page of Bank 0 RAM for shadowing writes to the YM2151 chip, and we've sliced off another 64 bytes for internal state for some of the API routines.

in the `audio/` subdirectory, we have two scripts that spit out ca65 code.  One (`create_luts.py`) is for creating the frequency lookup tables (`audio_luts.s`) used by some of the routines, and the other `fur2ymp.py` is for creating all of the instrument patches (`fmpatches.s`) from the one small binary data file in the `audio/` directory: `GM_X16.fur`.

`GM_X16.fur` is the data file containing the source of all of the instrument patches, and using [furnace](https://github.com/tildearrow/furnace/) is by far the easiest way to tweak and modify the instruments in the patch set. Thus I consider `GM_X16.fur` to be the closest thing to "source code" for this purpose, and I think it should be included in the repo for that reason.

The audio bank ($0A) has kernel API support included for user convenience, so machine language programs can switch to ROM bank $0A and still access the kernal jump table, similarly to how the BASIC bank can do the same.

Marking as a draft initially so that we can get more eyes for a bit before marking it as ready for review.

Following this PR, we expect to create another one with added BASIC keywords to make use of this new API.

### CODE REVIEW

**Comment by ZeroByteOrg** [comment]
Additionally, there will be a PR for x16-docs which updates the audio programming chapter to document the audio bank API.
https://github.com/mooinglemur/x16-docs/blob/20230101-audio/X16%20Reference%20-%2009%20-%20Sound%20Programming.md

**Comment by ZeroByteOrg** [comment]
Also, the intention is that once this new audio bank is approved and merged, that there is a PR to add several BASIC commands for audio, doing for sound what the graphics commands did for graphics. We felt that it made the most sense to keep the BASIC stuff separate from this PR.

**Comment by irmen** [comment]
This PR is the one that supersedes my smaller PR #364 that was meant to fix #330 initially.
The initialization code from that older PR is all in here as well and silences the audio chips on reset.

**Comment by mooinglemur** [comment]
This would close https://github.com/commanderx16/x16-rom/issues/328

**Comment by mooinglemur** [comment]
closing due to inclusion in X16Community fork

**Pull request closed without merging**
